title: "Ma page personnelle"
description: "Page en cours de construction"
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-paginate
paginate: 5 
minima:
  skin: classic
  nav:
    - title: "Accueil"
      url: /
    - title: "Général"
      url: /test/encore/
    - title: "Bof"
      url: /test/encore/
  social_links:
    - platform: github
      user_url: "https://github.com/emilienschultz"
timezone: Europe/Paris
lang: fr